export enum SyncOperationType {
  CHECKOUT = 'CHECKOUT',         // A sale completed while offline
  RETURN = 'RETURN',             // A return processed while offline
  CASH_MOVEMENT = 'CASH_MOVEMENT', // Expense or drop recorded while offline
  STOCK_COUNT = 'STOCK_COUNT',   // Physical count taken while offline
}

export enum SyncStatus {
  PENDING = 'PENDING',           // Sitting in the POS local queue
  PROCESSING = 'PROCESSING',
  APPLIED = 'APPLIED',           // Successfully merged into the central ledger
  CONFLICT = 'CONFLICT',         // Applied with overrides (manager decision required)
  REJECTED = 'REJECTED',         // Could not be applied (e.g., negative stock)
}

export enum ConflictStrategy {
  SERVER_WINS = 'SERVER_WINS',   // Server state is authoritative — discard POS value
  CLIENT_WINS = 'CLIENT_WINS',   // Offline POS value wins — override server state
  MANAGER_REVIEW = 'MANAGER_REVIEW', // Neither auto-resolved — flag for human intervention
}

/**
 * A single unit of work queued by the offline POS.
 * Must be idempotent: replaying the same operation multiple times must produce the same result.
 * The `clientGeneratedId` is the idempotency key.
 */
export interface SyncOperation {
  clientGeneratedId: string;  // UUID generated by the POS tablet — never overwritten
  branchId: string;
  userId: string;             // The cashier who performed the action offline
  type: SyncOperationType;
  payload: Record<string, any>;
  clientTimestamp: Date;      // When the POS user hit "Confirm" — stored for audit ordering
  status: SyncStatus;
  conflictDetails?: ConflictDetail;
  appliedAt?: Date;
  serverTimestamp?: Date;
}

export interface ConflictDetail {
  field: string;
  clientValue: any;
  serverValue: any;
  strategy: ConflictStrategy;
  resolvedBy?: string;          // userId of the manager who resolved it manually
  resolvedAt?: Date;
}

/**
 * The envelope the POS client sends when it reconnects to the network.
 */
export interface SyncBatch {
  batchId: string;              // Client-generated UUID for the entire batch
  deviceId: string;             // POS terminal identifier
  branchId: string;
  operations: SyncOperation[];
  sentAt: Date;
}
