export enum OrderSource {
  POS = 'POS',                 // Physical offline-first checkout
  ECOMMERCE = 'ECOMMERCE',     // Online storefront
  BACKOFFICE = 'BACKOFFICE',   // Manual entry from admin panel
}

export enum PaymentMethod {
  CASH = 'CASH',
  CREDIT_CARD = 'CREDIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CUSTOMER_CREDIT = 'CUSTOMER_CREDIT',
  MULTIPLE = 'MULTIPLE',
  QR_MERCADOPAGO = 'QR_MERCADOPAGO',
}

export interface OrderLineItem {
  id: string;
  variantId: string;
  categoryId: string;      
  quantity: number;
  basePrice: number;       // The price resolved before cart rules are applied
  discountAmount: number;  // Disocunt applied specifically to this line
  finalPrice: number;      // mathematically: basePrice - discountAmount
}

export interface SaleOrder {
  // CRITICAL ARCHITECTURE RULE: This ID is generated by the frontend Client (Vite/Dexie.js),
  // NOT the database. This allows the POS to safely retry sending the order 
  // if the internet connection drops without double-charging the customer.
  id: string; 
  
  branchId: string;
  source: OrderSource;
  customerId?: string;
  lines: OrderLineItem[];
  
  // Financial Totals calculated strictly by the Server Rules Engine
  subtotal: number;
  cartDiscountTotal: number; 
  grandTotal: number;
  
  appliedPromotions: string[];
  
  paymentMethod: PaymentMethod;
  paymentAccountId?: string; // The Treasury account that received the money
  
  createdAt: Date; // The exact millisecond the cashier hit "Charge" on the offline POS
  syncedAt: Date;  // The millisecond the server finally received and processed the data
}
