export enum OrderStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT', // Order generated, waiting for Stripe/MercadoPago webhook
  PAID = 'PAID',                       // Payment cleared, order drops into the warehouse queue
  PICKING = 'PICKING',                 // Warehouse worker is walking the aisles grabbing items
  PACKED = 'PACKED',                   // Items are in a box with a shipping label
  SHIPPED = 'SHIPPED',                 // Courier has physically taken the box
  DELIVERED = 'DELIVERED',             // Customer received the package
  CANCELLED = 'CANCELLED'              // Order aborted before shipping
}

/**
 * Manages the logistical lifecycle of an E-commerce order.
 * While POS orders complete instantly, online orders take days and require 
 * tracking across multiple warehouse states.
 */
export interface OrderFulfillment {
  id: string;
  saleOrderId: string; // Links back to the master SaleOrder generated by the SalesService
  status: OrderStatus;
  
  // Logistics
  trackingNumber?: string;
  courierName?: string; // e.g., 'FedEx', 'Andreani', 'MercadoEnvíos'
  
  // Timestamps for SLA tracking
  paidAt?: Date;
  pickedAt?: Date;
  packedAt?: Date;
  shippedAt?: Date;
  deliveredAt?: Date;
  
  createdAt: Date;
  updatedAt: Date;
}
